[package]
name = "telers-macros"
version = "1.0.0-beta.1"
edition = "2021"
description = "Macros for telers"
repository = "https://github.com/Desiders/telers"
license = "MIT OR Apache-2.0"
keywords = ["bot", "telegram", "telegram-bot", "telegram-bot-api", "telers"]
categories = ["web-programming", "api-bindings", "asynchronous"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lib]
proc-macro = true

[features]
default = []

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }
 
[dev-dependencies]
# This dependency is not necessarily the latest version
telers = { path = "../telers", features = ["default"] }
