[package]
name = "aiogram_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.86"
regex = "1.6"
futures = "0.3"
futures-core = "0.3"
pin-project-lite = "0.2.9"
log = "0.4"
async-recursion = "1.0.0"
async-channel = "1.7.1"
tokio = { version = "1.22.0", features = ["rt", "macros", "signal"] }
reqwest = { version = "0.11.12", features = ["json"] }
once_cell = "1.16.0"

[dev-dependencies]
serde_path_to_error = "0.1.8"
tokio-test = "0.4.2"
