[package]
name = "telers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.22", features = ["sync", "macros", "signal", "fs"] }
reqwest = { version = "0.11", features = ["multipart"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_with = "2.1"
futures = "0.3"
async-recursion = "1.0"
async-trait = "0.1"
once_cell = "1.16"
thiserror = "1.0"
anyhow = "1.0"
log = "0.4"
dashmap = "5.4"
regex = "1.6"
backoff = "0.4"
bytes = "1.3"
uuid = { version = "1.2", features = ["v4"] }

[dev-dependencies]
tokio-test = "0.4"
serde_path_to_error = "0.1.8"
pretty_env_logger = "0.4"
