[package]
name = "aiogram_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.86"
# reqwest = { version = "0.11.12", features = ["json"] }
regex = "1.6.0"
futures = "0.3"
futures-util = "0.3.25"
pin-project-lite = "0.2.9"

[dev-dependencies]
serde_path_to_error = "0.1.8"
tokio-test = "0.4.2"
