reorder_imports = true
reorder_modules = true
edition = "2021"
max_width = 100
fn_params_layout = "Tall"
hard_tabs = false
merge_derives = true
remove_nested_parens = true
tab_spaces = 4
use_field_init_shorthand = true
use_try_shorthand = true
