#![allow(clippy::too_many_lines)]

use crate::{
    file::camel_to_filename,
    generator::{
        doc_utils::{
            collect_telegram_type_names, link_known_type_mentions, normalize_doc_line_prefix,
        },
        helpers::{
            format_attr_description, format_description, get_singular_and_plural_forms,
            sanitize_field_name,
        },
    },
    parser::api::{NormalizedMethod, TypeKindInField},
};

use proc_macro2::{Ident, TokenStream};
use quote::{ToTokens, format_ident, quote};
use std::collections::{HashMap, HashSet};

struct MethodDocContext<'a> {
    schema_type_names: &'a HashSet<String>,
    api_method_names: &'a HashMap<String, String>,
}

#[must_use]
fn format_type_kind_rust(kind: &TypeKindInField) -> String {
    kind.to_token_stream().to_string().replace(' ', "")
}

#[must_use]
fn struct_name_to_method_name(name: &str) -> String {
    let mut chars = name.chars();
    let Some(first) = chars.next() else {
        return String::new();
    };
    first.to_lowercase().chain(chars).collect()
}

#[derive(Clone, Copy)]
enum PrepareStepKind {
    Single {
        function_name: &'static str,
        optional_binding: &'static str,
    },
    Group {
        function_name: &'static str,
        optional_binding: &'static str,
    },
}

#[must_use]
fn is_telegram_type(kind: &TypeKindInField, name: &str) -> bool {
    matches!(kind, TypeKindInField::Telegram(ty_name) if ty_name == name)
}

#[must_use]
fn is_array_of_telegram_type(kind: &TypeKindInField, name: &str) -> bool {
    matches!(
        kind,
        TypeKindInField::Array(inner)
            if matches!(inner.as_ref(), TypeKindInField::Telegram(ty_name) if ty_name == name)
    )
}

#[must_use]
fn get_prepare_step_kind(kind: &TypeKindInField) -> Option<PrepareStepKind> {
    let single = |function_name, optional_binding| PrepareStepKind::Single {
        function_name,
        optional_binding,
    };
    let group = |function_name, optional_binding| PrepareStepKind::Group {
        function_name,
        optional_binding,
    };

    // It's generated by AI. I will save it as a joke.
    #[allow(clippy::ignored_unit_patterns)]
    match () {
        _ if matches!(kind, TypeKindInField::InputFile) => Some(single("prepare_file", "file")),
        _ if is_telegram_type(kind, "InputMedia") => Some(single("prepare_input_media", "media")),
        _ if is_array_of_telegram_type(kind, "InputMedia") => {
            Some(group("prepare_input_media_group", "media"))
        }
        _ if is_telegram_type(kind, "InputSticker") => {
            Some(single("prepare_input_sticker", "sticker"))
        }
        _ if is_array_of_telegram_type(kind, "InputSticker") => {
            Some(group("prepare_input_stickers", "stickers"))
        }
        _ if is_telegram_type(kind, "InputPaidMedia") => {
            Some(single("prepare_input_paid_media", "media"))
        }
        _ if is_array_of_telegram_type(kind, "InputPaidMedia") => {
            Some(group("prepare_input_paid_media_group", "media"))
        }
        _ if is_telegram_type(kind, "InputStoryContent") => {
            Some(single("prepare_input_story_content", "content"))
        }
        _ if is_telegram_type(kind, "InputProfilePhoto") => {
            Some(single("prepare_input_profile_photo", "photo"))
        }
        _ if is_telegram_type(kind, "InputPollMedia") => {
            Some(single("prepare_input_poll_media", "media"))
        }
        _ if is_telegram_type(kind, "InputPollOptionMedia") => {
            Some(single("prepare_input_poll_option_media", "media"))
        }
        _ if is_array_of_telegram_type(kind, "InputPollOption") => {
            Some(group("prepare_input_poll_options", "options"))
        }
        _ if is_telegram_type(kind, "InputRichMessage") => {
            Some(single("prepare_input_rich_message", "rich_message"))
        }
        _ if is_array_of_telegram_type(kind, "InlineQueryResult") => {
            Some(group("prepare_inline_query_results", "results"))
        }
        _ => None,
    }
}

impl PrepareStepKind {
    #[must_use]
    fn required_tokens(self, field_name: &Ident) -> TokenStream {
        match self {
            Self::Single {
                function_name, ..
            } => {
                let function = format_ident!("{function_name}");
                quote! { super::#function(&mut files, &mut self.#field_name); }
            }
            Self::Group {
                function_name, ..
            } => {
                let function = format_ident!("{function_name}");
                quote! { super::#function(&mut files, self.#field_name.iter_mut().collect()); }
            }
        }
    }

    #[must_use]
    fn optional_tokens(self, field_name: &Ident) -> TokenStream {
        match self {
            Self::Single {
                function_name,
                optional_binding,
            } => {
                let function = format_ident!("{function_name}");
                let binding = format_ident!("{optional_binding}");
                quote! {
                    if let Some(#binding) = &mut self.#field_name {
                        super::#function(&mut files, #binding);
                    }
                }
            }
            Self::Group {
                function_name,
                optional_binding,
            } => {
                let function = format_ident!("{function_name}");
                let binding = format_ident!("{optional_binding}");
                quote! {
                    if let Some(#binding) = &mut self.#field_name {
                        super::#function(&mut files, #binding.iter_mut().collect());
                    }
                }
            }
        }
    }
}

#[must_use]
fn collect_prepare_steps(method_quote: &NormalizedMethod) -> Vec<TokenStream> {
    let mut steps = vec![];
    for field in &method_quote.fields {
        let name = sanitize_field_name(&field.name);
        let Some(kind) = get_prepare_step_kind(&field.r#type) else {
            continue;
        };
        let step = if field.required {
            kind.required_tokens(&name)
        } else {
            kind.optional_tokens(&name)
        };
        steps.push(step);
    }
    steps
}

#[must_use]
fn format_field_doc(
    description: &str,
    kind: &TypeKindInField,
    ctx: &MethodDocContext<'_>,
) -> String {
    let mut names = HashSet::new();
    collect_telegram_type_names(kind, &mut names);
    let doc = format_attr_description(description);
    let doc = link_known_type_mentions(&doc, &names);
    let doc = link_known_method_mentions(&doc, ctx);
    normalize_doc_line_prefix(&link_schema_type_mentions(&doc, ctx))
}

#[must_use]
fn format_field_arg_doc(
    field_name: &str,
    description: &str,
    kind: &TypeKindInField,
    ctx: &MethodDocContext<'_>,
) -> String {
    let doc = format_attr_description(&format!("* `{field_name}` - {description}"));
    let mut names = HashSet::new();
    collect_telegram_type_names(kind, &mut names);
    let doc = link_known_type_mentions(&doc, &names);
    let doc = link_known_method_mentions(&doc, ctx);
    normalize_doc_line_prefix(&link_schema_type_mentions(&doc, ctx))
}

#[must_use]
fn link_known_method_mentions(doc: &str, ctx: &MethodDocContext<'_>) -> String {
    doc.split_whitespace()
        .map(|token| {
            if token.contains("](") || token.starts_with("[`crate::methods::") {
                return token.to_string();
            }

            let start = token
                .find(|c: char| c.is_ascii_alphanumeric() || c == '`')
                .unwrap_or(0);
            let end = token
                .rfind(|c: char| c.is_ascii_alphanumeric() || c == '`')
                .map_or(token.len(), |idx| idx + 1);
            let (prefix, rest) = token.split_at(start);
            let (core, suffix) = rest.split_at(end.saturating_sub(start));

            let plain = core.trim_matches('`');
            if let Some(method_name) = ctx.api_method_names.get(plain) {
                return format!("{prefix}[`crate::methods::{method_name}`]{suffix}");
            }

            token.to_string()
        })
        .collect::<Vec<_>>()
        .join(" ")
}

#[must_use]
fn link_schema_type_mentions(doc: &str, ctx: &MethodDocContext<'_>) -> String {
    link_known_type_mentions(doc, ctx.schema_type_names)
}

fn collect_telegram_type_names_from_method(method: &NormalizedMethod, out: &mut HashSet<String>) {
    for field in &method.fields {
        collect_telegram_type_names(&field.r#type, out);
    }
    for ret in &method.returns {
        collect_telegram_type_names(ret, out);
    }
}

/// Builds method return type:
/// - `[]` -> `()`
/// - `[T]` -> `T`
/// - `[T1, T2, ...]` -> `Either<T1, Either<T2, ...>>`
#[must_use]
pub fn tokenize_method_return_type(returns: &[TypeKindInField]) -> TokenStream {
    let mut iter = returns.iter().map(|kind| quote! { #kind });
    let Some(first) = iter.next() else {
        return quote! { () };
    };
    iter.fold(first, |acc, next| quote! { crate::Either<#acc, #next> })
}

#[must_use]
fn builder_impl_for_method(
    method_quote: &NormalizedMethod,
    ctx: &MethodDocContext<'_>,
) -> TokenStream {
    let method_name = format_ident!("{}", method_quote.name);

    let fields: Box<[_]> = method_quote.fields.iter().collect();
    let required_fields: Box<[_]> = fields.iter().filter(|&&f| f.required).copied().collect();
    let optional_fields: Box<[_]> = fields.iter().filter(|&&f| !f.required).copied().collect();

    let new_method_ts = {
        let doc_creates =
            format_attr_description(&format!("Creates a new `{}`.", method_quote.name));
        let mut doc_lines = vec![quote! { #[doc = #doc_creates] }];

        if !required_fields.is_empty() {
            let doc_args = format_attr_description("# Arguments");
            doc_lines.push(quote! { #[doc = ""] #[doc = #doc_args] });
            for &field in &required_fields {
                let doc = format_field_arg_doc(&field.name, &field.description, &field.r#type, ctx);
                doc_lines.push(quote! { #[doc = #doc] });
            }
        }
        if !optional_fields.is_empty() {
            let doc_notes = format_attr_description("# Notes");
            let doc_opt = format_attr_description("Use builder methods to set optional fields.");
            doc_lines.push(quote! { #[doc = ""] #[doc = #doc_notes] #[doc = #doc_opt] });
        }

        if fields.is_empty() {
            quote! {
                #( #doc_lines )*
                #[must_use]
                pub const fn new() -> Self {
                    Self {}
                }
            }
        } else {
            let new_generics: Vec<_> = required_fields
                .iter()
                .enumerate()
                .flat_map(|(i, field)| {
                    let ty = &field.r#type;
                    let t = format_ident!("T{i}");
                    if let TypeKindInField::Array(inner) = ty {
                        let t_item = format_ident!("T{i}Item");
                        vec![
                            quote! { #t_item: Into<#inner> },
                            quote! { #t: IntoIterator<Item = #t_item> },
                        ]
                    } else {
                        vec![quote! { #t: Into<#ty> }]
                    }
                })
                .collect();
            let new_args: Vec<_> = required_fields
                .iter()
                .enumerate()
                .map(|(i, field)| {
                    let name = sanitize_field_name(&field.name);
                    let t = format_ident!("T{i}");
                    quote! { #name: #t }
                })
                .collect();
            let new_init = fields.iter().map(|field| {
                let name = sanitize_field_name(&field.name);
                if field.required {
                    if let TypeKindInField::Array(_) = &field.r#type {
                        quote! { #name: #name.into_iter().map(Into::into).collect() }
                    } else if field.is_recursive || field.is_boxed {
                        quote! { #name: Box::new(#name.into()) }
                    } else {
                        quote! { #name: #name.into() }
                    }
                } else {
                    quote! { #name: None }
                }
            });
            quote! {
                #( #doc_lines )*
                #[must_use]
                pub fn new<#( #new_generics ),*>(#( #new_args ),*) -> Self {
                    Self { #( #new_init, )* }
                }
            }
        }
    };

    let default_impl_ts = if required_fields.is_empty() {
        quote! {
            impl Default for #method_name {
                fn default() -> Self {
                    Self::new()
                }
            }
        }
    } else {
        quote! {}
    };

    let builder_methods_ts: Vec<_> = fields
        .iter()
        .flat_map(|field| {
            let mut methods = vec![];
            let name = sanitize_field_name(&field.name);
            let ty = &field.r#type;

            if let TypeKindInField::Array(inner) = ty {
                let (singular, plural) = get_singular_and_plural_forms(&field.name);
                let singular_name = sanitize_field_name(&singular);
                let plural_name = sanitize_field_name(&plural);

                let make_doc = |note: &str| {
                    let desc = format_field_doc(&field.description, &field.r#type, ctx);
                    let notes = format_attr_description("# Notes");
                    let note = format_attr_description(note);
                    quote! { #[doc = #desc] #[doc = ""] #[doc = #notes] #[doc = #note] }
                };
                let make_singular_body = |is_required: bool| -> TokenStream {
                    if is_required {
                        quote! {
                            self.#name = self.#name.into_vec().into_iter().chain(Some(val.into())).collect();
                            self
                        }
                    } else {
                        quote! {
                            self.#name = Some(self.#name.unwrap_or_default().into_vec().into_iter().chain(Some(val.into())).collect());
                            self
                        }
                    }
                };
                let make_plural_body = |is_required: bool| -> TokenStream {
                    if is_required {
                        quote! {
                            self.#name = self.#name.into_vec().into_iter().chain(val.into_iter().map(Into::into)).collect();
                            self
                        }
                    } else {
                        quote! {
                            self.#name = Some(self.#name.unwrap_or_default().into_vec().into_iter().chain(val.into_iter().map(Into::into)).collect());
                            self
                        }
                    }
                };

                let plural_doc = make_doc("Adds multiple elements.");
                let plural_body = make_plural_body(field.required);
                methods.push(quote! {
                    #plural_doc
                    #[must_use]
                    pub fn #plural_name<TItem: Into<#inner>, T: IntoIterator<Item = TItem>>(mut self, val: T) -> Self {
                        #plural_body
                    }
                });

                if singular_name != plural_name {
                    let singular_doc = make_doc("Adds a single element.");
                    let singular_body = make_singular_body(field.required);
                    methods.push(quote! {
                        #singular_doc
                        #[must_use]
                        pub fn #singular_name<T: Into<#inner>>(mut self, val: T) -> Self {
                            #singular_body
                        }
                    });
                }

                if !field.required {
                    let option_doc = make_doc("Adds multiple elements.");
                    let option_name = format_ident!("{}_option", field.name);
                    methods.push(quote! {
                        #option_doc
                        #[must_use]
                        pub fn #option_name<TItem: Into<#inner>, T: IntoIterator<Item = TItem>>(mut self, val: Option<T>) -> Self {
                            self.#name = val.map(|v| v.into_iter().map(Into::into).collect());
                            self
                        }
                    });
                }
            } else {
                let doc = format_field_doc(&field.description, &field.r#type, ctx);
                let boxed = field.is_recursive || field.is_boxed;
                let inner_value = if boxed {
                    quote! { Box::new(val.into()) }
                } else {
                    quote! { val.into() }
                };
                let value = if field.required {
                    inner_value.clone()
                } else {
                    quote! { Some(#inner_value) }
                };

                methods.push(quote! {
                    #[doc = #doc]
                    #[must_use]
                    pub fn #name<T: Into<#ty>>(mut self, val: T) -> Self {
                        self.#name = #value;
                        self
                    }
                });

                if !field.required {
                    let opt_value = if boxed {
                        quote! { val.map(|val| Box::new(val.into())) }
                    } else {
                        quote! { val.map(Into::into) }
                    };
                    let method_name = format_ident!("{}_option", field.name);
                    methods.push(quote! {
                        #[doc = #doc]
                        #[must_use]
                        pub fn #method_name<T: Into<#ty>>(mut self, val: Option<T>) -> Self {
                            self.#name = #opt_value;
                            self
                        }
                    });
                }
            }
            methods
        })
        .collect();

    quote! {
        impl #method_name {
            #new_method_ts
            #( #builder_methods_ts )*
        }
        #default_impl_ts
    }
}

#[must_use]
fn tokenize_telegram_method_impl(method_quote: &NormalizedMethod) -> TokenStream {
    let method_name = format_ident!("{}", method_quote.name);
    let method_api_name = struct_name_to_method_name(&method_quote.name);
    let return_type_tokens = tokenize_method_return_type(&method_quote.returns);
    let prepare_steps = collect_prepare_steps(method_quote);

    if prepare_steps.is_empty() {
        return quote! {
            impl super::TelegramMethod for #method_name {
                type Method = Self;
                type Return = #return_type_tokens;

                fn build_request<Client>(self, _bot: &Bot<Client>) -> super::Request<Self::Method> {
                    super::Request::new(#method_api_name, self, None)
                }
            }
        };
    }

    quote! {
        impl super::TelegramMethod for #method_name {
            type Method = Self;
            type Return = #return_type_tokens;

            fn build_request<Client>(mut self, _bot: &Bot<Client>) -> super::Request<Self::Method> {
                let mut files = vec![];
                #( #prepare_steps )*

                super::Request::new(#method_api_name, self, Some(files))
            }
        }
    }
}

#[must_use]
#[allow(clippy::implicit_hasher)]
pub fn tokenize_method(
    method_quote: &NormalizedMethod,
    known_schema_type_names: &HashSet<String>,
    known_api_method_names: &HashMap<String, String>,
) -> TokenStream {
    let ctx = MethodDocContext {
        schema_type_names: known_schema_type_names,
        api_method_names: known_api_method_names,
    };

    let import_quotes: Vec<_> = [
        Some(quote! { use crate::client::Bot; }),
        Some(quote! { use serde::Serialize; }),
    ]
    .into_iter()
    .flatten()
    .collect();

    let method_name = format_ident!("{}", method_quote.name);
    let mut doc_lines = format_description(&method_quote.description, &method_quote.href);
    let mut known_type_names = HashSet::new();
    collect_telegram_type_names_from_method(method_quote, &mut known_type_names);
    doc_lines = doc_lines
        .into_iter()
        .map(|line| {
            let line = link_known_type_mentions(&line, &known_type_names);
            link_schema_type_mentions(&line, &ctx)
        })
        .collect();
    let returns_doc: Vec<_> = if method_quote.returns.is_empty() {
        vec![]
    } else {
        let mut docs = vec![quote! { #[doc = " # Returns"] }];
        for return_type in &method_quote.returns {
            let line = format!(" - `{}`", format_type_kind_rust(return_type));
            docs.push(quote! { #[doc = #line] });
        }
        docs
    };
    let fields = method_quote.fields.iter().map(|field| {
        let name = sanitize_field_name(&field.name);
        let doc = format_field_doc(&field.description, &field.r#type, &ctx);
        let ty = &field.r#type;
        if field.required {
            quote! { #[doc = #doc] pub #name: #ty, }
        } else {
            quote! {
                #[doc = #doc]
                #[serde(skip_serializing_if = "Option::is_none")]
                pub #name: Option<#ty>,
            }
        }
    });
    let builder_impl = builder_impl_for_method(method_quote, &ctx);
    let telegram_method_impl = tokenize_telegram_method_impl(method_quote);

    quote! {
        #( #import_quotes )*

        #( #[doc = #doc_lines] )*
        #( #returns_doc )*
        #[derive(Clone, Debug, Serialize)]
        pub struct #method_name {
            #( #fields )*
        }

        #builder_impl
        #telegram_method_impl
    }
}

#[must_use]
pub fn tokenize_methods_mod(method_names: &[&String]) -> TokenStream {
    let mods_quote = method_names.iter().map(|&name| {
        let mod_name = format_ident!("{}", camel_to_filename(name, None));
        quote! { pub mod #mod_name; }
    });
    let uses_quote = method_names.iter().map(|&name| {
        let mod_name = format_ident!("{}", camel_to_filename(name, None));
        let method_name = format_ident!("{name}");
        quote! { pub use #mod_name::#method_name; }
    });

    quote! {
        //! Telegram Bot API methods and their request builders.
        //!
        //! This module re-exports all generated method structs from the `crate::methods` module.
        //! Each method follows a builder style:
        //! - required arguments are passed to `new(...)`
        //! - optional arguments are set by chainable builder methods
        //! - optional fields also have `_option(...)` variants to pass `Option<T>` directly
        //!   (including `None` to clear/unset a field)
        //!
        //! # Examples
        //! ```rust
        //! use telers::{methods::SendMessage, errors::SessionErrorKind, Bot};
        //!
        //! async fn send_text(bot: Bot) -> Result<(), SessionErrorKind> {
        //!     let request = SendMessage::new(1_i64, "Hello world!")
        //!         // Regular builder setter.
        //!         .disable_notification(true)
        //!         // `_option(...)` variant for Option<T> values.
        //!         .disable_notification_option(Some(true));
        //!
        //!     bot.send(request).await?;
        //!     Ok(())
        //! }
        //! ```

        pub(crate) mod non_telegram;
        pub use non_telegram::*;
        #( #mods_quote )*
        #( #uses_quote )*
    }
}
