[package]
name = "finite_state_machine"
version = "0.1.0"
edition = "2021"

[dependencies]
telers = { path = "../../telers", features = ["memory-storage"] }
tokio = { version = "1.28", features = ["macros"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }