[package]
name = "finite_state_machine"
version = "0.1.0"
edition = "2021"

[dependencies]
telers = { path = "../..", features = ["memory-storage"] }
tokio = { version = "1.28", features = ["macros"] }
log = "0.4"
pretty_env_logger = "0.4"
