[package]
name = "input_file"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
bytes = "1.3"
futures = "0.3"
reqwest = "0.13"
telers = { path = "../../telers", features = ["default_signal"] }
tokio = { version = "1.36", features = ["macros"] }
tokio-util = { version = "0.7.9", features = ["codec"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
