//! Internal helper macros shared between keyboard widget builders.
//!
//! These macros emit method bodies that would otherwise be copy-pasted across
//! several widget builders generated by `#[bon]`. They are intentionally
//! crate-private and only intended to be used inside the `widgets::kbd`
//! module tree.

/// Inject `header_row` / `header_push` / `footer_row` / `footer_push` helpers
/// on a `#[bon]` builder that owns `header_rows` and `footer_rows` as
/// `#[builder(field)]` vectors of button rows.
///
/// Used by the inline-keyboard collection widgets ([`Select`], [`Checkbox`],
/// [`Counter`], [`Multiselect`], [`Radio`], [`Toggle`]) so each one exposes the
/// same row-building surface without repeating method bodies.
///
/// [`Select`]: crate::widgets::Select
/// [`Checkbox`]: crate::widgets::Checkbox
/// [`Counter`]: crate::widgets::Counter
/// [`Multiselect`]: crate::widgets::Multiselect
/// [`Radio`]: crate::widgets::Radio
/// [`Toggle`]: crate::widgets::Toggle
macro_rules! impl_button_row_helpers {
    () => {
        /// Append a full row of buttons above the widget's primary body.
        pub fn header_row(
            mut self,
            buttons: impl IntoIterator<Item = $crate::widgets::Button>,
        ) -> Self {
            self.header_rows.push(buttons.into_iter().collect());
            self
        }

        /// Append a button to the last header row, creating a new row when none exists.
        pub fn header_push(mut self, button: $crate::widgets::Button) -> Self {
            match self.header_rows.last_mut() {
                Some(row) => row.push(button),
                None => self.header_rows.push(vec![button]),
            }
            self
        }

        /// Append a full row of buttons below the widget's primary body.
        pub fn footer_row(
            mut self,
            buttons: impl IntoIterator<Item = $crate::widgets::Button>,
        ) -> Self {
            self.footer_rows.push(buttons.into_iter().collect());
            self
        }

        /// Append a button to the last footer row, creating a new row when none exists.
        pub fn footer_push(mut self, button: $crate::widgets::Button) -> Self {
            match self.footer_rows.last_mut() {
                Some(row) => row.push(button),
                None => self.footer_rows.push(vec![button]),
            }
            self
        }
    };
}

pub(crate) use impl_button_row_helpers;

/// Inject the five `ReplyKeyboardMarkup`-shaped option setters on a `#[bon]`
/// builder that owns `options: ReplyKeyboardOptions` as a `#[builder(field)]`.
///
/// Used by [`RequestContact`], [`RequestLocation`], and [`RequestPoll`] so each
/// keyboard exposes the same set of layout flags without repeating method
/// bodies.
///
/// [`RequestContact`]: crate::widgets::RequestContact
/// [`RequestLocation`]: crate::widgets::RequestLocation
/// [`RequestPoll`]: crate::widgets::RequestPoll
macro_rules! impl_reply_keyboard_options_setters {
    () => {
        /// Request that the keyboard stays visible until the bot replaces it.
        #[allow(clippy::wrong_self_convention)]
        pub fn is_persistent(mut self, value: bool) -> Self {
            self.options.is_persistent = Some(value);
            self
        }

        /// Ask Telegram clients to resize the keyboard to fit the buttons.
        pub fn resize_keyboard(mut self, value: bool) -> Self {
            self.options.resize_keyboard = Some(value);
            self
        }

        /// Hide the keyboard after the user picks a button.
        pub fn one_time_keyboard(mut self, value: bool) -> Self {
            self.options.one_time_keyboard = Some(value);
            self
        }

        /// Set the input-field placeholder displayed while the keyboard is open.
        pub fn input_field_placeholder(
            mut self,
            value: impl Into<std::borrow::Cow<'static, str>>,
        ) -> Self {
            self.options.input_field_placeholder = Some(value.into());
            self
        }

        /// Restrict the keyboard to the message reply target or mentioned users only.
        pub fn selective(mut self, value: bool) -> Self {
            self.options.selective = Some(value);
            self
        }
    };
}

pub(crate) use impl_reply_keyboard_options_setters;
