[package]
name = "bot_http_client"
version = "0.1.0"
edition = "2021"

[dependencies]
telers = { path = "../..", features = ["default"] }
tokio = { version = "1.28", features = ["macros"] }
log = "0.4"
pretty_env_logger = "0.5"
async-trait = "0.1"
anyhow = "1.0"
