name: CI

env:
  CARGO_TERM_COLOR: always
  MSRV: '1.66'

on:
  push:
    branches:
    - dev-1.x
    - master
  pull_request: {}

permissions:
  contents: read

jobs:
  test-windows:
    name: Test Windows
    runs-on: windows-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test --lib --tests --all --all-features
  
  build-and-test-linux:
    name: Build Rust ${{matrix.rust}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@${{matrix.rust}}
      - name: Build
        run: cargo build --all --all-features
      - name: Test
        run: cargo test --lib --tests --all --all-features

  check:
    name: Check formatting and clippy
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
    - uses: actions/checkout@v4
    - uses: taiki-e/install-action@protoc
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy, rustfmt
    - uses: Swatinem/rust-cache@v2
    - name: Check
      run: cargo clippy --all --all-features -- -W clippy::pedantic
    - name: rustfmt
      run: cargo fmt --all --check
