name: CI

env:
  CARGO_TERM_COLOR: always

on:
  push:
    branches:
    - dev-1.x
    - master
  pull_request: {}

permissions:
  contents: read

jobs:
  test-windows:
    name: Test Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo test --lib --tests --all --all-features
  
  test-linux:
    name: Test Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Test
        run: cargo test --lib --tests --all --all-features

  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: taiki-e/install-action@v2
    - uses: dtolnay/rust-toolchain@nightly
      with:
        components: clippy, rustfmt
    - uses: Swatinem/rust-cache@v2
    - name: Check
      run: cargo clippy --all --all-features -- -W clippy::pedantic
    - name: rustfmt
      run: cargo fmt --all --check
  
  dependencies-are-sorted:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Install cargo-sort
      uses: taiki-e/install-action@v2
      with:
          tool: cargo-sort
    - name: Check that dependencies are sorted
      run: cargo sort --check --workspace --grouped
    
