[package]
name = "dialogs_force_reply"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
serde_json = "1.0"
telers = { path = "../../telers", features = ["default_signal", "memory-storage"] }
telers-dialog = { path = "../../telers-dialog" }
tokio = { version = "1.36", features = ["macros"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
